name: Android CI

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Android App
      run: bash ./gradlew assembleDebug --stacktrace
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: EVConData
        path: apk/app-debug.apk
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build debug apk
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Create release and upload apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: EVConData.apk
        asset_content_type: application/zip
